env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - tab
  quotes:
    - error
    - single
  linebreak-style:
    - error
    - unix
  space-before-blocks:
    - error
    - always
  keyword-spacing:
    - error
    - before: true
      after: true
  